// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.mungziapp.traveltogether.app;

import com.apollographql.apollo.api.Mutation;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ResponseFieldMapper;
import com.apollographql.apollo.api.ResponseFieldMarshaller;
import com.apollographql.apollo.api.ResponseReader;
import com.apollographql.apollo.api.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;
import com.apollographql.apollo.internal.QueryDocumentMinifier;
import com.apollographql.apollo.response.ScalarTypeAdapters;

import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;

import okio.BufferedSource;

import org.jetbrains.annotations.NotNull;

public final class FirstMutation implements Mutation<FirstMutation.Data, FirstMutation.Data, Operation.Variables> {
	public static final String OPERATION_ID = "0cd8836cc4c6c7fae291fd09749f16925fdd9ab9086cddb3929c37b554e68c5e";

	public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
			"mutation first {\n"
					+ "  oauthLogin(oauthInfo: {oauthId: \"1208434716\", oauthToken: \"XA-yZu1AVeNzU1a0vSNgJ8cQGN32VNqnn-dSngopdbIAAAFu5YckSg\", resourceServer: KAKAO}) {\n"
					+ "    __typename\n"
					+ "    accessToken\n"
					+ "    exp\n"
					+ "    refreshToken\n"
					+ "  }\n"
					+ "}"
	);

	public static final OperationName OPERATION_NAME = new OperationName() {
		@Override
		public String name() {
			return "first";
		}
	};

	private final Operation.Variables variables;

	public FirstMutation() {
		this.variables = Operation.EMPTY_VARIABLES;
	}

	@Override
	public String operationId() {
		return OPERATION_ID;
	}

	@Override
	public String queryDocument() {
		return QUERY_DOCUMENT;
	}

	@Override
	public FirstMutation.Data wrapData(FirstMutation.Data data) {
		return data;
	}

	@Override
	public Operation.Variables variables() {
		return variables;
	}

	@Override
	public ResponseFieldMapper<FirstMutation.Data> responseFieldMapper() {
		return new Data.Mapper();
	}

	public static Builder builder() {
		return new Builder();
	}

	@Override
	public OperationName name() {
		return OPERATION_NAME;
	}

	@Override
	@NotNull
	public Response<FirstMutation.Data> parse(@NotNull final BufferedSource source,
																						@NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
		return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
	}

	@Override
	@NotNull
	public Response<FirstMutation.Data> parse(@NotNull final BufferedSource source) throws
			IOException {
		return parse(source, ScalarTypeAdapters.DEFAULT);
	}

	public static final class Builder {
		Builder() {
		}

		public FirstMutation build() {
			return new FirstMutation();
		}
	}

	public static class Data implements Operation.Data {
		static final ResponseField[] $responseFields = {
				ResponseField.forObject("oauthLogin", "oauthLogin", new UnmodifiableMapBuilder<String, Object>(1)
						.put("oauthInfo", new UnmodifiableMapBuilder<String, Object>(3)
								.put("oauthId", "1208434716")
								.put("oauthToken", "XA-yZu1AVeNzU1a0vSNgJ8cQGN32VNqnn-dSngopdbIAAAFu5YckSg")
								.put("resourceServer", "KAKAO")
								.build())
						.build(), false, Collections.<ResponseField.Condition>emptyList())
		};

		final @NotNull
		OauthLogin oauthLogin;

		private transient volatile String $toString;

		private transient volatile int $hashCode;

		private transient volatile boolean $hashCodeMemoized;

		public Data(@NotNull OauthLogin oauthLogin) {
			this.oauthLogin = Utils.checkNotNull(oauthLogin, "oauthLogin == null");
		}

		public @NotNull
		OauthLogin oauthLogin() {
			return this.oauthLogin;
		}

		@SuppressWarnings("unchecked")
		public ResponseFieldMarshaller marshaller() {
			return new ResponseFieldMarshaller() {
				@Override
				public void marshal(ResponseWriter writer) {
					writer.writeObject($responseFields[0], oauthLogin.marshaller());
				}
			};
		}

		@Override
		public String toString() {
			if ($toString == null) {
				$toString = "Data{"
						+ "oauthLogin=" + oauthLogin
						+ "}";
			}
			return $toString;
		}

		@Override
		public boolean equals(Object o) {
			if (o == this) {
				return true;
			}
			if (o instanceof Data) {
				Data that = (Data) o;
				return this.oauthLogin.equals(that.oauthLogin);
			}
			return false;
		}

		@Override
		public int hashCode() {
			if (!$hashCodeMemoized) {
				int h = 1;
				h *= 1000003;
				h ^= oauthLogin.hashCode();
				$hashCode = h;
				$hashCodeMemoized = true;
			}
			return $hashCode;
		}

		public static final class Mapper implements ResponseFieldMapper<Data> {
			final OauthLogin.Mapper oauthLoginFieldMapper = new OauthLogin.Mapper();

			@Override
			public Data map(ResponseReader reader) {
				final OauthLogin oauthLogin = reader.readObject($responseFields[0], new ResponseReader.ObjectReader<OauthLogin>() {
					@Override
					public OauthLogin read(ResponseReader reader) {
						return oauthLoginFieldMapper.map(reader);
					}
				});
				return new Data(oauthLogin);
			}
		}
	}

	public static class OauthLogin {
		static final ResponseField[] $responseFields = {
				ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
				ResponseField.forString("accessToken", "accessToken", null, false, Collections.<ResponseField.Condition>emptyList()),
				ResponseField.forDouble("exp", "exp", null, false, Collections.<ResponseField.Condition>emptyList()),
				ResponseField.forString("refreshToken", "refreshToken", null, false, Collections.<ResponseField.Condition>emptyList())
		};

		final @NotNull
		String __typename;

		final @NotNull
		String accessToken;

		final double exp;

		final @NotNull
		String refreshToken;

		private transient volatile String $toString;

		private transient volatile int $hashCode;

		private transient volatile boolean $hashCodeMemoized;

		public OauthLogin(@NotNull String __typename, @NotNull String accessToken, double exp,
											@NotNull String refreshToken) {
			this.__typename = Utils.checkNotNull(__typename, "__typename == null");
			this.accessToken = Utils.checkNotNull(accessToken, "accessToken == null");
			this.exp = exp;
			this.refreshToken = Utils.checkNotNull(refreshToken, "refreshToken == null");
		}

		public @NotNull
		String __typename() {
			return this.__typename;
		}

		public @NotNull
		String accessToken() {
			return this.accessToken;
		}

		public double exp() {
			return this.exp;
		}

		public @NotNull
		String refreshToken() {
			return this.refreshToken;
		}

		@SuppressWarnings("unchecked")
		public ResponseFieldMarshaller marshaller() {
			return new ResponseFieldMarshaller() {
				@Override
				public void marshal(ResponseWriter writer) {
					writer.writeString($responseFields[0], __typename);
					writer.writeString($responseFields[1], accessToken);
					writer.writeDouble($responseFields[2], exp);
					writer.writeString($responseFields[3], refreshToken);
				}
			};
		}

		@Override
		public String toString() {
			if ($toString == null) {
				$toString = "OauthLogin{"
						+ "__typename=" + __typename + ", "
						+ "accessToken=" + accessToken + ", "
						+ "exp=" + exp + ", "
						+ "refreshToken=" + refreshToken
						+ "}";
			}
			return $toString;
		}

		@Override
		public boolean equals(Object o) {
			if (o == this) {
				return true;
			}
			if (o instanceof OauthLogin) {
				OauthLogin that = (OauthLogin) o;
				return this.__typename.equals(that.__typename)
						&& this.accessToken.equals(that.accessToken)
						&& Double.doubleToLongBits(this.exp) == Double.doubleToLongBits(that.exp)
						&& this.refreshToken.equals(that.refreshToken);
			}
			return false;
		}

		@Override
		public int hashCode() {
			if (!$hashCodeMemoized) {
				int h = 1;
				h *= 1000003;
				h ^= __typename.hashCode();
				h *= 1000003;
				h ^= accessToken.hashCode();
				h *= 1000003;
				h ^= Double.valueOf(exp).hashCode();
				h *= 1000003;
				h ^= refreshToken.hashCode();
				$hashCode = h;
				$hashCodeMemoized = true;
			}
			return $hashCode;
		}

		public static final class Mapper implements ResponseFieldMapper<OauthLogin> {
			@Override
			public OauthLogin map(ResponseReader reader) {
				final String __typename = reader.readString($responseFields[0]);
				final String accessToken = reader.readString($responseFields[1]);
				final double exp = reader.readDouble($responseFields[2]);
				final String refreshToken = reader.readString($responseFields[3]);
				return new OauthLogin(__typename, accessToken, exp, refreshToken);
			}
		}
	}
}
