package com.mungziapp.traveltogether.app;

import android.content.Context;

import com.mungziapp.traveltogether.R;
import com.mungziapp.traveltogether.data.TravelRoom;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

public class TravelHelper {
    public static HashMap<String, List<String>> countryMap = new HashMap<>();
    private static TravelHelper instance = new TravelHelper();

    public static TravelHelper getInstance() { return instance; }

    private TravelHelper() {
        List<List<String>> countries = new ArrayList<>();

        countries.add(Arrays.asList("알바니아", "\uD83C\uDDE6\uD83C\uDDF1", ""));
        countries.add(Arrays.asList("알바니아", "\uD83C\uDDE6\uD83C\uDDF1", ""));
        countries.add(Arrays.asList("아르메니아", "\uD83C\uDDE6\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("앙골라", "\uD83C\uDDE6\uD83C\uDDF4", ""));
        countries.add(Arrays.asList("남극", "\uD83C\uDDE6\uD83C\uDDF6", ""));
        countries.add(Arrays.asList("아르헨티나", "\uD83C\uDDE6\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("아메리칸사모아", "\uD83C\uDDE6\uD83C\uDDF8", ""));
        countries.add(Arrays.asList("오스트리아", "\uD83C\uDDE6\uD83C\uDDF9", ""));
        countries.add(Arrays.asList("호주", "\uD83C\uDDE6\uD83C\uDDFA", ""));
        countries.add(Arrays.asList("아루바", "\uD83C\uDDE6\uD83C\uDDFC", ""));
        countries.add(Arrays.asList("올란드제도", "\uD83C\uDDE6\uD83C\uDDFD", ""));
        countries.add(Arrays.asList("아제르바이잔", "\uD83C\uDDE6\uD83C\uDDFF", ""));
        countries.add(Arrays.asList("보스니아헤르체고비나", "\uD83C\uDDE7\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("바베이도스", "\uD83C\uDDE7\uD83C\uDDE7", ""));
        countries.add(Arrays.asList("방글라데시", "\uD83C\uDDE7\uD83C\uDDE9", ""));
        countries.add(Arrays.asList("벨기에", "\uD83C\uDDE7\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("부르키나파소", "\uD83C\uDDE7\uD83C\uDDEB", ""));
        countries.add(Arrays.asList("불가리아", "\uD83C\uDDE7\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("바레인", "\uD83C\uDDE7\uD83C\uDDED", ""));
        countries.add(Arrays.asList("부룬디", "\uD83C\uDDE7\uD83C\uDDEE", ""));
        countries.add(Arrays.asList("베냉", "\uD83C\uDDE7\uD83C\uDDEF", ""));
        countries.add(Arrays.asList("버뮤다", "\uD83C\uDDE7\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("브루나이", "\uD83C\uDDE7\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("볼리비아", "\uD83C\uDDE7\uD83C\uDDF4", ""));
        countries.add(Arrays.asList("카리브해네덜란드", "\uD83C\uDDE7\uD83C\uDDF6", ""));
        countries.add(Arrays.asList("브라질", "\uD83C\uDDE7\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("바하마", "\uD83C\uDDE7\uD83C\uDDF8", ""));
        countries.add(Arrays.asList("부탄", "\uD83C\uDDE7\uD83C\uDDF9", ""));
        countries.add(Arrays.asList("보츠와나", "\uD83C\uDDE7\uD83C\uDDFC", ""));
        countries.add(Arrays.asList("벨로루시", "\uD83C\uDDE7\uD83C\uDDFE", ""));
        countries.add(Arrays.asList("벨리즈", "\uD83C\uDDE7\uD83C\uDDFF", ""));
        countries.add(Arrays.asList("캐나다", "\uD83C\uDDE8\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("코코스군도", "\uD83C\uDDE8\uD83C\uDDE8", ""));
        countries.add(Arrays.asList("콩고민주공화국", "\uD83C\uDDE8\uD83C\uDDE9", ""));
        countries.add(Arrays.asList("중앙아프리카공화국", "\uD83C\uDDE8\uD83C\uDDEB", ""));
        countries.add(Arrays.asList("콩고-브라자빌", "\uD83C\uDDE8\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("스위스", "\uD83C\uDDE8\uD83C\uDDED", ""));
        countries.add(Arrays.asList("코트디부아르", "\uD83C\uDDE8\uD83C\uDDEE", ""));
        countries.add(Arrays.asList("쿡제도", "\uD83C\uDDE8\uD83C\uDDF0", ""));
        countries.add(Arrays.asList("칠레", "\uD83C\uDDE8\uD83C\uDDF1", ""));
        countries.add(Arrays.asList("카메룬", "\uD83C\uDDE8\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("중국", "\uD83C\uDDE8\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("콜롬비아", "\uD83C\uDDE8\uD83C\uDDF4", ""));
        countries.add(Arrays.asList("코스타리카", "\uD83C\uDDE8\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("쿠바", "\uD83C\uDDE8\uD83C\uDDFA", ""));
        countries.add(Arrays.asList("카보베르데", "\uD83C\uDDE8\uD83C\uDDFB", ""));
        countries.add(Arrays.asList("크리스마스섬", "\uD83C\uDDE8\uD83C\uDDFD", ""));
        countries.add(Arrays.asList("키프로스", "\uD83C\uDDE8\uD83C\uDDFE", ""));
        countries.add(Arrays.asList("체코", "\uD83C\uDDE8\uD83C\uDDFF", ""));
        countries.add(Arrays.asList("독일", "\uD83C\uDDE9\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("디에고가르시아", "\uD83C\uDDE9\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("지부티", "\uD83C\uDDE9\uD83C\uDDEF", ""));
        countries.add(Arrays.asList("덴마크", "\uD83C\uDDE9\uD83C\uDDF0", ""));
        countries.add(Arrays.asList("도미니카", "\uD83C\uDDE9\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("도미니카공화국", "\uD83C\uDDE9\uD83C\uDDF4", ""));
        countries.add(Arrays.asList("알제리아", "\uD83C\uDDE9\uD83C\uDDFF", ""));
        countries.add(Arrays.asList("세우타&멜리야", "\uD83C\uDDEA\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("에콰도르", "\uD83C\uDDEA\uD83C\uDDE8", ""));
        countries.add(Arrays.asList("에스토니아", "\uD83C\uDDEA\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("이집트", "\uD83C\uDDEA\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("서사하라", "\uD83C\uDDEA\uD83C\uDDED", ""));
        countries.add(Arrays.asList("에리트레아", "\uD83C\uDDEA\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("스페인", "\uD83C\uDDEA\uD83C\uDDF8", ""));
        countries.add(Arrays.asList("이디오피아", "\uD83C\uDDEA\uD83C\uDDF9", ""));
        countries.add(Arrays.asList("유럽 연합", "\uD83C\uDDEA\uD83C\uDDFA", ""));
        countries.add(Arrays.asList("핀란드", "\uD83C\uDDEB\uD83C\uDDEE", ""));
        countries.add(Arrays.asList("피지", "\uD83C\uDDEB\uD83C\uDDEF", ""));
        countries.add(Arrays.asList("포클랜드 제도", "\uD83C\uDDEB\uD83C\uDDF0", ""));
        countries.add(Arrays.asList("미크로네시아", "\uD83C\uDDEB\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("페로 제도", "\uD83C\uDDEB\uD83C\uDDF4", ""));
        countries.add(Arrays.asList("프랑스", "\uD83C\uDDEB\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("가봉", "\uD83C\uDDEC\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("영국", "\uD83C\uDDEC\uD83C\uDDE7", ""));
        countries.add(Arrays.asList("그레나다", "\uD83C\uDDEC\uD83C\uDDE9", ""));
        countries.add(Arrays.asList("조지아", "\uD83C\uDDEC\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("프랑스령기아나", "\uD83C\uDDEC\uD83C\uDDEB", ""));
        countries.add(Arrays.asList("건지 섬", "\uD83C\uDDEC\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("가나", "\uD83C\uDDEC\uD83C\uDDED", ""));
        countries.add(Arrays.asList("지브롤터", "\uD83C\uDDEC\uD83C\uDDEE", ""));
        countries.add(Arrays.asList("그린란드", "\uD83C\uDDEC\uD83C\uDDF1", ""));
        countries.add(Arrays.asList("감비아", "\uD83C\uDDEC\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("기니", "\uD83C\uDDEC\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("과들루프", "\uD83C\uDDEC\uD83C\uDDF5", ""));
        countries.add(Arrays.asList("적도기니", "\uD83C\uDDEC\uD83C\uDDF6", ""));
        countries.add(Arrays.asList("그리스", "\uD83C\uDDEC\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("과테말라", "\uD83C\uDDEC\uD83C\uDDF9", ""));
        countries.add(Arrays.asList("괌", "\uD83C\uDDEC\uD83C\uDDFA", ""));
        countries.add(Arrays.asList("비사우", "\uD83C\uDDEC\uD83C\uDDFC", ""));
        countries.add(Arrays.asList("가이아나", "\uD83C\uDDEC\uD83C\uDDFE", ""));
        countries.add(Arrays.asList("홍콩", "\uD83C\uDDED\uD83C\uDDF0", ""));
        countries.add(Arrays.asList("허드맥도날드제도", "\uD83C\uDDED\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("온두라스", "\uD83C\uDDED\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("크로아티아", "\uD83C\uDDED\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("아이티", "\uD83C\uDDED\uD83C\uDDF9", ""));
        countries.add(Arrays.asList("헝가리", "\uD83C\uDDED\uD83C\uDDFA", ""));
        countries.add(Arrays.asList("카나리아제도", "\uD83C\uDDEE\uD83C\uDDE8", ""));
        countries.add(Arrays.asList("인도네시아", "\uD83C\uDDEE\uD83C\uDDE9", ""));
        countries.add(Arrays.asList("아일랜드", "\uD83C\uDDEE\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("이스라엘", "\uD83C\uDDEE\uD83C\uDDF1", ""));
        countries.add(Arrays.asList("맨섬", "\uD83C\uDDEE\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("인도", "\uD83C\uDDEE\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("영국령 인도양 영토", "\uD83C\uDDEE\uD83C\uDDF4", ""));
        countries.add(Arrays.asList("이라크", "\uD83C\uDDEE\uD83C\uDDF6", ""));
        countries.add(Arrays.asList("이란", "\uD83C\uDDEE\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("아이슬란드", "\uD83C\uDDEE\uD83C\uDDF8", ""));
        countries.add(Arrays.asList("이탈리아", "\uD83C\uDDEE\uD83C\uDDF9", ""));
        countries.add(Arrays.asList("저지", "\uD83C\uDDEF\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("자메이카", "\uD83C\uDDEF\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("요르단", "\uD83C\uDDEF\uD83C\uDDF4", ""));
        countries.add(Arrays.asList("일본", "\uD83C\uDDEF\uD83C\uDDF5", ""));
        countries.add(Arrays.asList("케냐", "\uD83C\uDDF0\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("키르기즈스탄", "\uD83C\uDDF0\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("캄보디아", "\uD83C\uDDF0\uD83C\uDDED", ""));
        countries.add(Arrays.asList("키리바시", "\uD83C\uDDF0\uD83C\uDDEE", ""));
        countries.add(Arrays.asList("코모로", "\uD83C\uDDF0\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("세인트 키츠 네비스", "\uD83C\uDDF0\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("북한", "\uD83C\uDDF0\uD83C\uDDF5", ""));
        countries.add(Arrays.asList("한국", "\uD83C\uDDF0\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("쿠웨이트", "\uD83C\uDDF0\uD83C\uDDFC", ""));
        countries.add(Arrays.asList("케이맨 제도", "\uD83C\uDDF0\uD83C\uDDFE", ""));
        countries.add(Arrays.asList("카자흐스탄", "\uD83C\uDDF0\uD83C\uDDFF", ""));
        countries.add(Arrays.asList("라오스", "\uD83C\uDDF1\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("레바논", "\uD83C\uDDF1\uD83C\uDDE7", ""));
        countries.add(Arrays.asList("세인트 루시아", "\uD83C\uDDF1\uD83C\uDDE8", ""));
        countries.add(Arrays.asList("리히텐슈타인", "\uD83C\uDDF1\uD83C\uDDEE", ""));
        countries.add(Arrays.asList("스리랑카", "\uD83C\uDDF1\uD83C\uDDF0", ""));
        countries.add(Arrays.asList("라이베리아", "\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("레소토", "\uD83C\uDDF1\uD83C\uDDF8", ""));
        countries.add(Arrays.asList("리투아니아", "\uD83C\uDDF1\uD83C\uDDF9", ""));
        countries.add(Arrays.asList("룩셈부르크", "\uD83C\uDDF1\uD83C\uDDFA", ""));
        countries.add(Arrays.asList("라트비아", "\uD83C\uDDF1\uD83C\uDDFB", ""));
        countries.add(Arrays.asList("리비아", "\uD83C\uDDF1\uD83C\uDDFE", ""));
        countries.add(Arrays.asList("모로코", "\uD83C\uDDF2\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("모나코", "\uD83C\uDDF2\uD83C\uDDE8", ""));
        countries.add(Arrays.asList("몰도바", "\uD83C\uDDF2\uD83C\uDDE9", ""));
        countries.add(Arrays.asList("몬테네그로", "\uD83C\uDDF2\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("세인트 마틴", "\uD83C\uDDF2\uD83C\uDDEB", ""));
        countries.add(Arrays.asList("마다가스카르", "\uD83C\uDDF2\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("마샬 군도", "\uD83C\uDDF2\uD83C\uDDED", ""));
        countries.add(Arrays.asList("북 마케도니아", "\uD83C\uDDF2\uD83C\uDDF0", ""));
        countries.add(Arrays.asList("말리", "\uD83C\uDDF2\uD83C\uDDF1", ""));
        countries.add(Arrays.asList("미얀마", "\uD83C\uDDF2\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("몽골", "\uD83C\uDDF2\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("북 마리아나 군도", "\uD83C\uDDF2\uD83C\uDDF5", ""));
        countries.add(Arrays.asList("마르티니크", "\uD83C\uDDF2\uD83C\uDDF6", ""));
        countries.add(Arrays.asList("모리타니", "\uD83C\uDDF2\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("몬트 세 라트", "\uD83C\uDDF2\uD83C\uDDF8", ""));
        countries.add(Arrays.asList("말타", "\uD83C\uDDF2\uD83C\uDDF9", ""));
        countries.add(Arrays.asList("모리셔스", "\uD83C\uDDF2\uD83C\uDDFA", ""));
        countries.add(Arrays.asList("몰디브", "\uD83C\uDDF2\uD83C\uDDFB", ""));
        countries.add(Arrays.asList("말라위", "\uD83C\uDDF2\uD83C\uDDFC", ""));
        countries.add(Arrays.asList("멕시코", "\uD83C\uDDF2\uD83C\uDDFD", ""));
        countries.add(Arrays.asList("말레이시아", "\uD83C\uDDF2\uD83C\uDDFE", ""));
        countries.add(Arrays.asList("모잠비크", "\uD83C\uDDF2\uD83C\uDDFF", ""));
        countries.add(Arrays.asList("나미비아", "\uD83C\uDDF3\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("뉴 칼레도니아", "\uD83C\uDDF3\uD83C\uDDE8", ""));
        countries.add(Arrays.asList("니제르", "\uD83C\uDDF3\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("노퍽 섬", "\uD83C\uDDF3\uD83C\uDDEB", ""));
        countries.add(Arrays.asList("나이지리아", "\uD83C\uDDF3\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("니카라구아", "\uD83C\uDDF3\uD83C\uDDEE", ""));
        countries.add(Arrays.asList("네덜란드", "\uD83C\uDDF3\uD83C\uDDF1", ""));
        countries.add(Arrays.asList("노르웨이", "\uD83C\uDDF3\uD83C\uDDF4", ""));
        countries.add(Arrays.asList("네팔", "\uD83C\uDDF3\uD83C\uDDF5", ""));
        countries.add(Arrays.asList("나우루", "\uD83C\uDDF3\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("니우에", "\uD83C\uDDF3\uD83C\uDDFA", ""));
        countries.add(Arrays.asList("뉴질랜드", "\uD83C\uDDF3\uD83C\uDDFF", ""));
        countries.add(Arrays.asList("오만", "\uD83C\uDDF4\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("파나마", "\uD83C\uDDF5\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("페루", "\uD83C\uDDF5\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("프랑스 령 폴리네시아", "\uD83C\uDDF5\uD83C\uDDEB", ""));
        countries.add(Arrays.asList("파푸아 뉴기니", "\uD83C\uDDF5\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("필리핀", "\uD83C\uDDF5\uD83C\uDDED", ""));
        countries.add(Arrays.asList("파키스탄", "\uD83C\uDDF5\uD83C\uDDF0", ""));
        countries.add(Arrays.asList("폴란드", "\uD83C\uDDF5\uD83C\uDDF1", ""));
        countries.add(Arrays.asList("핏 케언 제도", "\uD83C\uDDF5\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("푸에르토 리코", "\uD83C\uDDF5\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("팔레스타인 영토", "\uD83C\uDDF5\uD83C\uDDF8", ""));
        countries.add(Arrays.asList("포르투갈", "\uD83C\uDDF5\uD83C\uDDF9", ""));
        countries.add(Arrays.asList("팔라우", "\uD83C\uDDF5\uD83C\uDDFC", ""));
        countries.add(Arrays.asList("파라과이", "\uD83C\uDDF5\uD83C\uDDFE", ""));
        countries.add(Arrays.asList("카타르", "\uD83C\uDDF6\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("레위니옹", "\uD83C\uDDF7\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("루마니아", "\uD83C\uDDF7\uD83C\uDDF4", ""));
        countries.add(Arrays.asList("세르비아", "\uD83C\uDDF7\uD83C\uDDF8", ""));
        countries.add(Arrays.asList("러시아", "\uD83C\uDDF7\uD83C\uDDFA", ""));
        countries.add(Arrays.asList("르완다", "\uD83C\uDDF7\uD83C\uDDFC", ""));
        countries.add(Arrays.asList("사우디 아라비아", "\uD83C\uDDF8\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("솔로몬 제도", "\uD83C\uDDF8\uD83C\uDDE7", ""));
        countries.add(Arrays.asList("세이셸", "\uD83C\uDDF8\uD83C\uDDE8", ""));
        countries.add(Arrays.asList("수단", "\uD83C\uDDF8\uD83C\uDDE9", ""));
        countries.add(Arrays.asList("스웨덴", "\uD83C\uDDF8\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("싱가포르", "\uD83C\uDDF8\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("슬로베니아", "\uD83C\uDDF8\uD83C\uDDEE", ""));
        countries.add(Arrays.asList("슬로바키아", "\uD83C\uDDF8\uD83C\uDDF0", ""));
        countries.add(Arrays.asList("시에라 리온", "\uD83C\uDDF8\uD83C\uDDF1", ""));
        countries.add(Arrays.asList("세네갈", "\uD83C\uDDF8\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("소말리아", "\uD83C\uDDF8\uD83C\uDDF4", ""));
        countries.add(Arrays.asList("수리남", "\uD83C\uDDF8\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("남 수단", "\uD83C\uDDF8\uD83C\uDDF8", ""));
        countries.add(Arrays.asList("엘살바도르", "\uD83C\uDDF8\uD83C\uDDFB", ""));
        countries.add(Arrays.asList("시리아", "\uD83C\uDDF8\uD83C\uDDFE", ""));
        countries.add(Arrays.asList("스와질란드", "\uD83C\uDDF8\uD83C\uDDFF", ""));
        countries.add(Arrays.asList("투르크 & 카이 코스 군도", "\uD83C\uDDF9\uD83C\uDDE8", ""));
        countries.add(Arrays.asList("차드", "\uD83C\uDDF9\uD83C\uDDE9", ""));
        countries.add(Arrays.asList("프랑스 남부 영토", "\uD83C\uDDF9\uD83C\uDDEB", ""));
        countries.add(Arrays.asList("토고", "\uD83C\uDDF9\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("태국", "\uD83C\uDDF9\uD83C\uDDED", ""));
        countries.add(Arrays.asList("타지키스탄", "\uD83C\uDDF9\uD83C\uDDEF", ""));
        countries.add(Arrays.asList("토켈 라우", "\uD83C\uDDF9\uD83C\uDDF0", ""));
        countries.add(Arrays.asList("동 티모르", "\uD83C\uDDF9\uD83C\uDDF1", ""));
        countries.add(Arrays.asList("투르크 메니스탄", "\uD83C\uDDF9\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("튀니지", "\uD83C\uDDF9\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("통가", "\uD83C\uDDF9\uD83C\uDDF4", ""));
        countries.add(Arrays.asList("터키", "\uD83C\uDDF9\uD83C\uDDF7", ""));
        countries.add(Arrays.asList("트리니다드 토바고", "\uD83C\uDDF9\uD83C\uDDF9", ""));
        countries.add(Arrays.asList("투발루", "\uD83C\uDDF9\uD83C\uDDFB", ""));
        countries.add(Arrays.asList("대만", "\uD83C\uDDF9\uD83C\uDDFC", ""));
        countries.add(Arrays.asList("탄자니아", "\uD83C\uDDF9\uD83C\uDDFF", ""));
        countries.add(Arrays.asList("우크라이나", "\uD83C\uDDFA\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("우간다", "\uD83C\uDDFA\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("유엔", "\uD83C\uDDFA\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("미국", "\uD83C\uDDFA\uD83C\uDDF8", ""));
        countries.add(Arrays.asList("우루과이", "\uD83C\uDDFA\uD83C\uDDFE", ""));
        countries.add(Arrays.asList("우즈베키스탄", "\uD83C\uDDFA\uD83C\uDDFF", ""));
        countries.add(Arrays.asList("바티칸 시티", "\uD83C\uDDFB\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("베네수엘라", "\uD83C\uDDFB\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("영국령 버진 아일랜드", "\uD83C\uDDFB\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("미국령 버진 아일랜드", "\uD83C\uDDFB\uD83C\uDDEE", ""));
        countries.add(Arrays.asList("베트남", "\uD83C\uDDFB\uD83C\uDDF3", ""));
        countries.add(Arrays.asList("바누아투", "\uD83C\uDDFB\uD83C\uDDFA", ""));
        countries.add(Arrays.asList("사모아", "\uD83C\uDDFC\uD83C\uDDF8", ""));
        countries.add(Arrays.asList("코소보", "\uD83C\uDDFD\uD83C\uDDF0", ""));
        countries.add(Arrays.asList("예멘", "\uD83C\uDDFE\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("남아프리카", "\uD83C\uDDFF\uD83C\uDDE6", ""));
        countries.add(Arrays.asList("잠비아", "\uD83C\uDDFF\uD83C\uDDF2", ""));
        countries.add(Arrays.asList("짐바브웨", "\uD83C\uDDFF\uD83C\uDDFC", ""));
        countries.add(Arrays.asList("안도라", "\uD83C\uDDE6\uD83C\uDDE9", ""));
        countries.add(Arrays.asList("아랍에미리트", "\uD83C\uDDE6\uD83C\uDDEA", ""));
        countries.add(Arrays.asList("아프가니스탄", "\uD83C\uDDE6\uD83C\uDDEB", ""));
        countries.add(Arrays.asList("앤티가바부다", "\uD83C\uDDE6\uD83C\uDDEC", ""));
        countries.add(Arrays.asList("앵귈라", "\uD83C\uDDE6\uD83C\uDDEE", ""));
        countries.add(Arrays.asList("스코틀란드", "\uD83C\uDFF4\uDB40\uDC67\uDB40\uDC62\uDB40\uDC73\uDB40\uDC63\uDB40\uDC74\uDB40\uDC7F", ""));
        countries.add(Arrays.asList("웨일즈", "\uD83C\uDFF4\uDB40\uDC67\uDB40\uDC62\uDB40\uDC77\uDB40\uDC6C\uDB40\uDC73\uDB40\uDC7F", ""));

        for (List<String> country: countries) {
            countryMap.put(country.get(0), Arrays.asList(country.get(1), country.get(2)));
        }
    }

    public static void init(Context context) {
        DatabaseManager.openDatabase(context);
        //DatabaseManager.dropTables();
        DatabaseManager.createTables();
        DatabaseManager.insertDummyData(makeTravelRoom());
    }

    private static List<TravelRoom> makeTravelRoom() {
        String countries = "\uD83C\uDDF0\uD83C\uDDF7,\uD83C\uDDFA\uD83C\uDDF8,\uD83C\uDDED\uD83C\uDDF0,\uD83C\uDDEB\uD83C\uDDF7" +
                ",\uD83C\uDDEC\uD83C\uDDFA,\uD83C\uDDFB\uD83C\uDDF3,\uD83C\uDDF2\uD83C\uDDF4,\uD83C\uDDF3\uD83C\uDDF5" +
                ",\uD83C\uDDEC\uD83C\uDDF9,\uD83C\uDDEC\uD83C\uDDE9,\uD83C\uDDEC\uD83C\uDDF7,\uD83C\uDDEC\uD83C\uDDF1";
        String countries2 = "";
        String countries3 = "\uD83C\uDDF7\uD83C\uDDFA";

        int members = 9;
        int members2 = 1;
        int members3 = 2;

        List<TravelRoom> travelRooms = new ArrayList<>();
        travelRooms.add(new TravelRoom(1, "엄마와 함께하는 4박 5일 홍콩여행", "20.01.12","20.01.16", countries, R.drawable.travel_room_sample_01, members));
        travelRooms.add(new TravelRoom(2, "친구들과 처음가는 배낭 여행", "2019.12.09", "19.12.29", countries2, R.drawable.travel_room_sample_02, members2));
        travelRooms.add(new TravelRoom(3, "마카오로 호캉스~~!!", "19.10.11", "19.10.15", countries3, R.drawable.travel_room_sample_03, members3));
        travelRooms.add(new TravelRoom(4, "앗싸 퇴직여행 ✈️", "19.08.15", "19.08.18", countries, R.drawable.travel_room_sample_04, members));
        travelRooms.add(new TravelRoom(5, "혼자가는 러시아 일주 \uD83C\uDFA1", "19.07.12", "19.07.16", countries2, R.drawable.travel_room_sample_01, members2));
        travelRooms.add(new TravelRoom(6, "찐친들 - 미국 횡단 일주", "19.06.09", "19.06.29", countries3, R.drawable.travel_room_sample_02, members3));

        travelRooms.add(new TravelRoom(7, "가치 같이 여행", "18.10.12", "18.10.16", countries2, R.drawable.travel_room_sample_05, members2));
        travelRooms.add(new TravelRoom(8, "일주일 제주 여행", "18.06.09", "19.06.29", countries3, R.drawable.travel_room_sample_06, members3));
        travelRooms.add(new TravelRoom(9, "내일로 전국 일주~~", "18.02.11", "18.02.15", countries, R.drawable.travel_room_sample_07, members));
        travelRooms.add(new TravelRoom(10, "가자 파리로~!", "17.12.15", "17.12.28", countries2, R.drawable.travel_room_sample_01, members2));
        travelRooms.add(new TravelRoom(11, "얄리얄리얄라셩 얄라리얄라", "17.10.12", "17.10.16", countries3, R.drawable.travel_room_sample_05, members3));
        travelRooms.add(new TravelRoom(12, "일주일 제주 여행", "17.06.09", "17.06.29", countries, R.drawable.travel_room_sample_06, members));
        travelRooms.add(new TravelRoom(13, "내일로 전국 일주~~", "17.02.11", "17.02.15", countries2, R.drawable.travel_room_sample_07, members2));
        travelRooms.add(new TravelRoom(14, "가자 파리로~!", "16.08.19", "16.09.02", countries3, R.drawable.travel_room_sample_01, members3));

        return travelRooms;
    }
}
